services:
  database:
    image: mysql:8.0
    container_name: sisteped_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "DB!pass00"
      MYSQL_DATABASE: "sisteped"
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: